import { Star, Zap, Crown } from "lucide-react";

export const plans = [
	{
		id: "basic",
		name: "Paket Pelajar",
		description: "Cocok untuk anda yang sedang mengerjakan tugas.",
		monthlyPrice: 500000,
		annualPrice: 500000,
		icon: Star,
		color: "from-blue-500 to-cyan-500",
		features: [
			"Website Responsif",
			"3 Halaman",
			"Domain Gratis 1 Tahun",
			"SSL Certificate",
			"Email Support",
			"SEO Dasar",
		],
		popular: false,
		buttonText: "Pilih Paket",
	},
	{
		id: "business",
		name: "Bisnis Promosi",
		description: "Bagi anda yang ingin mempromosikan bisnis anda.",
		monthlyPrice: 3000000,
		annualPrice: 3000000,
		icon: Zap,
		color: "from-purple-500 to-pink-500",
		features: [
			"Semua fitur Dasar",
			"10 Halaman",
			"E-commerce Ready",
			"Analytics Dashboard",
			"Live Chat Support",
			"SEO Premium",
			"Social Media Integration",
			"Monthly Report",
		],
		popular: true,
		buttonText: "Mulai Sekarang",
	},
	{
		id: "enterprise",
		name: "Perusahaan",
		description: "Solusi lengkap untuk perusahaan besar",
		monthlyPrice: 10000000,
		annualPrice: 10000000,
		icon: Crown,
		color: "from-orange-500 to-red-500",
		features: [
			"Semua fitur Profesional",
			"Unlimited Halaman",
			"Custom Development",
			"Priority Support 24/7",
			"Advanced Analytics",
			"Multi-language Support",
			"API Integration",
			"Dedicated Account Manager",
		],
		popular: false,
		buttonText: "Hubungi Sales",
	},
];
