import { Quicksand } from "next/font/google";
import "@tabler/icons-webfont/dist/tabler-icons.min.css";
import "./globals.css";

const quicksand = Quicksand({
	variable: "--font-quicksand",
	subsets: ["latin"],
});

export const metadata = {
	title: "rexivo.id",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${quicksand.variable} antialiased`}>{children}</body>
		</html>
	);
}
